
import Providers from '@/contexts/Providers';
import { Theme } from '@radix-ui/themes';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Script from "next/script";
import NavBar from './componentes/NavBar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: "/favicon.ico",

}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="pt-br">
      <body className='min-h-screen  ' suppressHydrationWarning={true}>
      <Theme>
        <Providers>
        <Script
              strategy="lazyOnload"
              src={`https://www.googletagmanager.com/gtag/js?id=G-19VJCQS2H4`}
            />
            <Script strategy="lazyOnload" id="gtag-script">
              {`
                      window.dataLayer = window.dataLayer || [];
                      function gtag(){dataLayer.push(arguments);}
                      gtag('js', new Date());
                      gtag('config', 'G-19VJCQS2H4', {
                      page_path: window.location.pathname,
                      });
                  `}
            </Script>
            <NavBar />
        <div className='min-h-screen overflow-x-hidden'>
        
               {children}
        </div>
        </Providers>
      </Theme>
      </body>
    </html>
  )
}
