// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupplyManager.App;

#nullable disable

namespace SupplyManager.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20240416002847_v42")]
    partial class v42
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SupplyManager.Models.AtividadeRd", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlsFotos")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AtividadesRd");
                });

            modelBuilder.Entity("SupplyManager.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPFOrCNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Empresa")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereço")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SupplyManager.Models.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bairro")
                        .HasColumnType("longtext");

                    b.Property<string>("Cep")
                        .HasColumnType("longtext");

                    b.Property<string>("Cidade")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Numero")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Fornecedores");
                });

            modelBuilder.Entity("SupplyManager.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime");

                    b.Property<float?>("Estoque")
                        .HasColumnType("float");

                    b.Property<int?>("MaterialId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<float?>("Movimentacao")
                        .HasColumnType("float");

                    b.Property<string>("Razao")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsavel")
                        .HasColumnType("longtext");

                    b.Property<float?>("SaldoFinal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("SupplyManager.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdicaoItem")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataAlteracaoItem")
                        .HasColumnType("datetime");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("OrdemServicoId")
                        .HasColumnType("int");

                    b.Property<float?>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("ResponsavelAdicao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelMudanca")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("SupplyManager.Models.ItemNotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("AliquotaICMS")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AliquotaIPI")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("ItensNotaFiscal");
                });

            modelBuilder.Entity("SupplyManager.Models.ItemOrcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAdicaoItem")
                        .HasColumnType("datetime");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecoItemOrcamento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("QuantidadeMaterial")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("ItensOrcamento");
                });

            modelBuilder.Entity("SupplyManager.Models.LogAcoesUsuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Acao")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAcao")
                        .HasColumnType("datetime");

                    b.Property<string>("Responsavel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LogAcoesUsuarios");
                });

            modelBuilder.Entity("SupplyManager.Models.Material", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoFabricante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext");

                    b.Property<string>("Corrente")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataEntradaNF")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Localizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<float?>("Markup")
                        .HasColumnType("float");

                    b.Property<float?>("PrecoCusto")
                        .HasColumnType("float");

                    b.Property<float?>("PrecoVenda")
                        .HasColumnType("float");

                    b.Property<string>("Tensao")
                        .HasColumnType("longtext");

                    b.Property<string>("Unidade")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImage")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("SupplyManager.Models.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("BaseCalculoICMS")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CFOP")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataEmissaoNF")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Frete")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NumeroNF")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ValorICMS")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("NotasFiscais");
                });

            modelBuilder.Entity("SupplyManager.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("Acrescimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CpfOrCnpj")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataOrcamento")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataVenda")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Empresa")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsPayed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeOrcamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrecoVendaComDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PrecoVendaTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ResponsavelOrcamento")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoPagamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("SupplyManager.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAbertura")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NumeroOs")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrecoCustoTotalOs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PrecoVendaTotalOs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ResponsaveisExecucao")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelAbertura")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelAutorizacao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OrdemServicos");
                });

            modelBuilder.Entity("SupplyManager.Models.RelatorioDiario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Contato")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataRD")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HorarioAbertura")
                        .HasColumnType("datetime");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<bool?>("isFinished")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("RelatorioDiarios");
                });

            modelBuilder.Entity("SupplyManager.Models.Usuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataCadastro")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<bool>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Usuários");
                });

            modelBuilder.Entity("SupplyManager.Models.Cliente", b =>
                {
                    b.HasOne("SupplyManager.Models.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("SupplyManager.Models.Inventario", b =>
                {
                    b.HasOne("SupplyManager.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");
                });

            modelBuilder.Entity("SupplyManager.Models.Item", b =>
                {
                    b.HasOne("SupplyManager.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyManager.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("SupplyManager.Models.ItemNotaFiscal", b =>
                {
                    b.HasOne("SupplyManager.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyManager.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("SupplyManager.Models.ItemOrcamento", b =>
                {
                    b.HasOne("SupplyManager.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupplyManager.Models.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Orcamento");
                });
#pragma warning restore 612, 618
        }
    }
}
