/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forms` | `/forms`; params?: Router.UnknownInputParams; } | { pathname: `/api/apiClient`; params?: Router.UnknownInputParams; } | { pathname: `/api/formService`; params?: Router.UnknownInputParams; } | { pathname: `/data/database`; params?: Router.UnknownInputParams; } | { pathname: `/data/filledFormRepository`; params?: Router.UnknownInputParams; } | { pathname: `/data/formTemplates`; params?: Router.UnknownInputParams; } | { pathname: `/data/templateService`; params?: Router.UnknownInputParams; } | { pathname: `/models/FormTypes`; params?: Router.UnknownInputParams; } | { pathname: `/services/syncService`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/forms/fill/[instanceId]` | `/forms/fill/[instanceId]`, params: Router.UnknownInputParams & { instanceId: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/forms` | `/forms`; params?: Router.UnknownOutputParams; } | { pathname: `/api/apiClient`; params?: Router.UnknownOutputParams; } | { pathname: `/api/formService`; params?: Router.UnknownOutputParams; } | { pathname: `/data/database`; params?: Router.UnknownOutputParams; } | { pathname: `/data/filledFormRepository`; params?: Router.UnknownOutputParams; } | { pathname: `/data/formTemplates`; params?: Router.UnknownOutputParams; } | { pathname: `/data/templateService`; params?: Router.UnknownOutputParams; } | { pathname: `/models/FormTypes`; params?: Router.UnknownOutputParams; } | { pathname: `/services/syncService`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } } | { pathname: `${'/(tabs)'}/forms/fill/[instanceId]` | `/forms/fill/[instanceId]`, params: Router.UnknownOutputParams & { instanceId: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/explore${`?${string}` | `#${string}` | ''}` | `/explore${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/forms${`?${string}` | `#${string}` | ''}` | `/forms${`?${string}` | `#${string}` | ''}` | `/api/apiClient${`?${string}` | `#${string}` | ''}` | `/api/formService${`?${string}` | `#${string}` | ''}` | `/data/database${`?${string}` | `#${string}` | ''}` | `/data/filledFormRepository${`?${string}` | `#${string}` | ''}` | `/data/formTemplates${`?${string}` | `#${string}` | ''}` | `/data/templateService${`?${string}` | `#${string}` | ''}` | `/models/FormTypes${`?${string}` | `#${string}` | ''}` | `/services/syncService${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/explore` | `/explore`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/forms` | `/forms`; params?: Router.UnknownInputParams; } | { pathname: `/api/apiClient`; params?: Router.UnknownInputParams; } | { pathname: `/api/formService`; params?: Router.UnknownInputParams; } | { pathname: `/data/database`; params?: Router.UnknownInputParams; } | { pathname: `/data/filledFormRepository`; params?: Router.UnknownInputParams; } | { pathname: `/data/formTemplates`; params?: Router.UnknownInputParams; } | { pathname: `/data/templateService`; params?: Router.UnknownInputParams; } | { pathname: `/models/FormTypes`; params?: Router.UnknownInputParams; } | { pathname: `/services/syncService`; params?: Router.UnknownInputParams; } | `/+not-found` | `${'/(tabs)'}/forms/fill/${Router.SingleRoutePart<T>}` | `/forms/fill/${Router.SingleRoutePart<T>}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } } | { pathname: `${'/(tabs)'}/forms/fill/[instanceId]` | `/forms/fill/[instanceId]`, params: Router.UnknownInputParams & { instanceId: string | number; } };
    }
  }
}
