// <auto-generated />
using System;
using MasterErp.Infraestructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterErp.Infraestructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20240529011614_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MasterErp.Domain.Models.AtividadeRd", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumeroAtividade")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int?>("RelatorioRdId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioRdId");

                    b.ToTable("AtividadesRd");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPFOrCNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereço")
                        .HasColumnType("longtext");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ImagemAtividadeRd", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AtividadeRdId")
                        .HasColumnType("int");

                    b.Property<string>("DataAdicao")
                        .HasColumnType("longtext");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeRdId");

                    b.ToTable("ImagensAtividadeRd");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime");

                    b.Property<float?>("Estoque")
                        .HasColumnType("float");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<float?>("Movimentacao")
                        .HasColumnType("float");

                    b.Property<string>("Razao")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsavel")
                        .HasColumnType("longtext");

                    b.Property<float?>("SaldoFinal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAdicaoItem")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataAlteracaoItem")
                        .HasColumnType("datetime");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("OrdemServicoId")
                        .HasColumnType("int");

                    b.Property<float?>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("ResponsavelAdicao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelMudanca")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ItemNotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AliquotaICMS")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("AliquotaIPI")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("NotaFiscalId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Quantidade")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("ValorUnitario")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("NotaFiscalId");

                    b.ToTable("ItensNotaFiscal");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ItemOrcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAdicaoItem")
                        .HasColumnType("datetime");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecoItemOrcamento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("QuantidadeMaterial")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("ItensOrcamento");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.LogAcoesUsuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Acao")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAcao")
                        .HasColumnType("datetime");

                    b.Property<string>("Responsavel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LogAcoesUsuarios");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Material", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoFabricante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext");

                    b.Property<string>("Corrente")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataEntradaNF")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Localizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<float?>("Markup")
                        .HasColumnType("float");

                    b.Property<float?>("PrecoCusto")
                        .HasColumnType("float");

                    b.Property<float?>("PrecoVenda")
                        .HasColumnType("float");

                    b.Property<string>("Tensao")
                        .HasColumnType("longtext");

                    b.Property<string>("Unidade")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.NotaFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("BaseCalculoICMS")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CFOP")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataEmissaoNF")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Frete")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NumeroNF")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("ValorICMS")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("NotasFiscais");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Acrescimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CpfOrCnpj")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataOrcamento")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataVenda")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Empresa")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsPayed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeOrcamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrecoVendaComDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PrecoVendaTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ResponsavelOrcamento")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoPagamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAbertura")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NumeroOs")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrecoCustoTotalOs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PrecoVendaTotalOs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ResponsaveisExecucao")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelAbertura")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelAutorizacao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OrdemServicos");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.RelatorioDiario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Contato")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataRD")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HorarioAbertura")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("HorarioFechamento")
                        .HasColumnType("datetime");

                    b.Property<string>("ResponsavelAbertura")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelFechamento")
                        .HasColumnType("longtext");

                    b.Property<bool?>("isFinished")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("RelatorioDiarios");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.TarefaUsuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("NomeTarefa")
                        .HasColumnType("longtext");

                    b.Property<string>("Prioridade")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Status")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TarefaUsuarios");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Usuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataCadastrado")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<bool?>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Usuários");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.AtividadeRd", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.RelatorioDiario", "RelatorioDiario")
                        .WithMany()
                        .HasForeignKey("RelatorioRdId");

                    b.Navigation("RelatorioDiario");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Cliente", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ImagemAtividadeRd", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.AtividadeRd", "AtividadeRd")
                        .WithMany()
                        .HasForeignKey("AtividadeRdId");

                    b.Navigation("AtividadeRd");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Inventario", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Item", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterErp.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ItemNotaFiscal", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterErp.Domain.Models.NotaFiscal", "NotaFiscal")
                        .WithMany()
                        .HasForeignKey("NotaFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("NotaFiscal");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ItemOrcamento", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterErp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.TarefaUsuario", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });
#pragma warning restore 612, 618
        }
    }
}
