// <auto-generated />
using System;
using MasterErp.Infraestructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MasterErp.Infraestructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    partial class SqlContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MasterErp.Domain.Models.AtividadeRd", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("DataAtividade")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<int?>("NumeroAtividade")
                        .HasColumnType("int");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<int?>("RelatorioRdId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RelatorioRdId");

                    b.ToTable("AtividadesRd");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPFOrCNPJ")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereço")
                        .HasColumnType("longtext");

                    b.Property<int>("MyProperty")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FilledFormInstance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DeviceCreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DeviceSubmittedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FilledByUserId")
                        .HasColumnType("int");

                    b.Property<int>("FormTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("FormTemplateVersion")
                        .HasColumnType("int");

                    b.Property<string>("GeneralObservations")
                        .HasColumnType("longtext");

                    b.Property<string>("HeaderDataJson")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime?>("ServerReceivedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SignatureBase64")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SyncErrorMessage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.HasIndex("FilledByUserId", "Status");

                    b.ToTable("FilledFormInstances");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FilledItemResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("FilledFormInstanceId")
                        .HasColumnType("char(36)");

                    b.Property<int>("FormTemplateItemId")
                        .HasColumnType("int");

                    b.Property<string>("ObservationText")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponseValue")
                        .HasColumnType("longtext");

                    b.Property<string>("SignatureValueBase64")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FilledFormInstanceId");

                    b.HasIndex("FormTemplateItemId");

                    b.ToTable("FilledItemResponses");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FormTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("FormTemplates");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FormTemplateItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DefaultValue")
                        .HasColumnType("longtext");

                    b.Property<int?>("FormTemplateIdAsHeader")
                        .HasColumnType("int");

                    b.Property<int?>("FormTemplateSectionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("OptionsJson")
                        .HasColumnType("json");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Placeholder")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateIdAsHeader");

                    b.HasIndex("FormTemplateSectionId");

                    b.ToTable("FormTemplateItems");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FormTemplateSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FormTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormTemplateId");

                    b.ToTable("FormTemplateSections");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ImagemAtividadeRd", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<int?>("AtividadeRdId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAdicao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImagem")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AtividadeRdId");

                    b.ToTable("ImagensAtividadeRd");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Inventario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAlteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<float?>("Estoque")
                        .HasColumnType("float");

                    b.Property<int?>("MaterialId")
                        .HasColumnType("int");

                    b.Property<float?>("Movimentacao")
                        .HasColumnType("float");

                    b.Property<string>("Razao")
                        .HasColumnType("longtext");

                    b.Property<string>("Responsavel")
                        .HasColumnType("longtext");

                    b.Property<float?>("SaldoFinal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.ToTable("Inventarios");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAdicaoItem")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataAlteracaoItem")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("OrdemServicoId")
                        .HasColumnType("int");

                    b.Property<float?>("Quantidade")
                        .HasColumnType("float");

                    b.Property<string>("ResponsavelAdicao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelMudanca")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrdemServicoId");

                    b.ToTable("Itens");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ItemOrcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAdicaoItem")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MaterialId")
                        .HasColumnType("int");

                    b.Property<int>("OrcamentoId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PrecoItemOrcamento")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("QuantidadeMaterial")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("OrcamentoId");

                    b.ToTable("ItensOrcamento");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.LogAcoesUsuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Acao")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAcao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Responsavel")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LogAcoesUsuarios");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Material", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Categoria")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoFabricante")
                        .HasColumnType("longtext");

                    b.Property<string>("CodigoInterno")
                        .HasColumnType("longtext");

                    b.Property<string>("Corrente")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataEntradaNF")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<string>("Localizacao")
                        .HasColumnType("longtext");

                    b.Property<string>("Marca")
                        .HasColumnType("longtext");

                    b.Property<float?>("Markup")
                        .HasColumnType("float");

                    b.Property<float?>("PrecoCusto")
                        .HasColumnType("float");

                    b.Property<float?>("PrecoVenda")
                        .HasColumnType("float");

                    b.Property<string>("Tensao")
                        .HasColumnType("longtext");

                    b.Property<string>("Unidade")
                        .HasColumnType("longtext");

                    b.Property<string>("UrlImage")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Materiais");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Orcamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Acrescimo")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CpfOrCnpj")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataOrcamento")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataVenda")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("Desconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("EmailCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("Empresa")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsPayed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NomeCliente")
                        .HasColumnType("longtext");

                    b.Property<string>("NomeOrcamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrecoVendaComDesconto")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PrecoVendaTotal")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ResponsavelOrcamento")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelVenda")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoPagamento")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Orcamentos");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.OrdemServico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataAutorizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsAuthorized")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("NumeroOs")
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("PrecoCustoTotalOs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("PrecoVendaTotalOs")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("ResponsaveisExecucao")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelAbertura")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelAutorizacao")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("OrdemServicos");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.RelatorioDiario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Cnpj")
                        .HasColumnType("longtext");

                    b.Property<string>("Contato")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataRD")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Empresa")
                        .HasColumnType("longtext");

                    b.Property<string>("Endereco")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("HorarioAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("HorarioFechamento")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ResponsavelAbertura")
                        .HasColumnType("longtext");

                    b.Property<string>("ResponsavelFechamento")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasColumnType("longtext");

                    b.Property<bool?>("isFinished")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("RelatorioDiarios");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.TarefaUsuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<DateTime?>("DataTarefa")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NomeTarefa")
                        .HasColumnType("longtext");

                    b.Property<string>("Prioridade")
                        .HasColumnType("longtext");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<bool?>("isFinished")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TarefaUsuarios");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Usuario", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Cargo")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataCadastrado")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.Property<string>("Senha")
                        .HasColumnType("longtext");

                    b.Property<bool?>("isActive")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Usuários");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.AtividadeRd", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.RelatorioDiario", "RelatorioDiario")
                        .WithMany()
                        .HasForeignKey("RelatorioRdId");

                    b.Navigation("RelatorioDiario");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Cliente", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FilledFormInstance", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Usuario", "FilledByUser")
                        .WithMany()
                        .HasForeignKey("FilledByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MasterErp.Domain.Models.Forms.FormTemplate", "FormTemplate")
                        .WithMany()
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FilledByUser");

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FilledItemResponse", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Forms.FilledFormInstance", "FilledFormInstance")
                        .WithMany("Responses")
                        .HasForeignKey("FilledFormInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterErp.Domain.Models.Forms.FormTemplateItem", "FormTemplateItem")
                        .WithMany()
                        .HasForeignKey("FormTemplateItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FilledFormInstance");

                    b.Navigation("FormTemplateItem");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FormTemplate", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Usuario", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FormTemplateItem", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Forms.FormTemplate", "FormTemplateAsHeader")
                        .WithMany("HeaderFields")
                        .HasForeignKey("FormTemplateIdAsHeader")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MasterErp.Domain.Models.Forms.FormTemplateSection", "FormTemplateSection")
                        .WithMany("Items")
                        .HasForeignKey("FormTemplateSectionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("FormTemplateAsHeader");

                    b.Navigation("FormTemplateSection");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FormTemplateSection", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Forms.FormTemplate", "FormTemplate")
                        .WithMany("Sections")
                        .HasForeignKey("FormTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FormTemplate");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ImagemAtividadeRd", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.AtividadeRd", "AtividadeRd")
                        .WithMany()
                        .HasForeignKey("AtividadeRdId");

                    b.Navigation("AtividadeRd");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Inventario", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Item", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterErp.Domain.Models.OrdemServico", "OrdemServico")
                        .WithMany()
                        .HasForeignKey("OrdemServicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("OrdemServico");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.ItemOrcamento", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Material", "Material")
                        .WithMany()
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MasterErp.Domain.Models.Orcamento", "Orcamento")
                        .WithMany()
                        .HasForeignKey("OrcamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Orcamento");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.TarefaUsuario", b =>
                {
                    b.HasOne("MasterErp.Domain.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FilledFormInstance", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FormTemplate", b =>
                {
                    b.Navigation("HeaderFields");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("MasterErp.Domain.Models.Forms.FormTemplateSection", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
